version: '3.8'

services:
  movieapi:

    build: 
      context: .

    ports:
      - "1985:8000"

    volumes:
      - ./app:/app

    command: >
     sh -c "python movieapi/manage.py wait_for_db && 
            python  movieapi/manage.py migrate &&
            python  movieapi/manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=movieapi
      - DB_USER=postgres
      - DB_PASS=secretcredentials123
    
    depends_on:
      - db
    
    networks:
      - djangonetwork

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=movieapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretcredentials123
    
    networks:
      - djangonetwork

networks:
      djangonetwork:
          driver: bridge